update dependency installer scripts

diff --git a/dependencies/common/install-boost b/dependencies/common/install-boost
--- a/dependencies/common/install-boost
+++ b/dependencies/common/install-boost
@@ -3,7 +3,7 @@
 #
 # install-boost
 #
-# Copyright (C) 2022 by Posit Software, PBC
+# Copyright (C) 2025 by Posit Software, PBC
 #
 # Unless you have received this program directly from Posit Software pursuant
 # to the terms of a commercial license agreement with Posit Software, then
@@ -17,132 +17,75 @@
 
 set -e
 
+# The version of Boost to be downloaded and built.
+BOOST_VERSION=1.87.0
+
 source "$(dirname "${BASH_SOURCE[0]}")/../tools/rstudio-tools.sh"
-section "Installing Boost"
+section "Installing Boost [${BOOST_VERSION}]"
 
-# install dir
-INSTALL_DIR=$(pwd)
-
-# determine platform
-PLATFORM=$(uname)
+OWD=$(pwd)
 
 # constants
-BOOST_VERSION_NUMBER=1.87.0
-BOOST_VERSION=boost_1_87_0
-BOOST_TAR=$BOOST_VERSION.tar.bz2
-BOOST_BUILD_DIR=boost-build
-BOOST_MODULES=(
-   algorithm asio array bind build chrono circular_buffer config context crc
-   date_time filesystem foreach format function interprocess iostreams
-   lambda lexical_cast optional program_options predef property_tree random range ref
-   regex scope_exit signals signals2 smart_ptr spirit string_algo system
-   test thread tokenizer type_traits typeof unordered utility variant
-)
+BOOST_FOLDER="boost_${BOOST_VERSION//./_}"
+BOOST_TARBALL="${BOOST_FOLDER}.tar.bz2"
+BOOST_PREFIX="${RSTUDIO_TOOLS_ROOT}/boost/${BOOST_FOLDER}"
+BOOST_URL="${RSTUDIO_BUILDTOOLS}/Boost/${BOOST_TARBALL}"
+BOOST_BUILDDIR="/tmp/rstudio-build/${BOOST_FOLDER}"
 
-# compute boost dir
-BOOST_DIR="${RSTUDIO_TOOLS_ROOT}/boost/${BOOST_VERSION}"
-
-
-if [ "${PLATFORM}" = "Darwin" ]; then
-   TOOLSET="toolset=clang-darwin"
+# help Boost find correct libraries with Homebrew
+if command -v brew &> /dev/null ; then
+   BREW_PREFIX="$(brew --prefix)"
+   BOOST_EXTRA="include=${BREW_PREFIX}/include library-path=${BREW_PREFIX}/lib"
 fi
 
 # install if we aren't already installed
-if [ -e "${BOOST_DIR}" ]; then
-   info "Boost ${BOOST_VERSION_NUMBER} already installed at '${BOOST_DIR}'"
+if [ -e "${BOOST_PREFIX}" ]; then
+   info "Boost ${BOOST_VERSION} already installed at '${BOOST_PREFIX}'"
    exit 0
 fi
 
 # re-run as root if necessary
 sudo-if-necessary-for "${RSTUDIO_TOOLS_ROOT}" "$@"
 
-# move to tempdir for build
-TEMP_DIR="$(mktemp -d)"
-cd "${TEMP_DIR}"
+# dump the BOOST variables we've defined
+declare -p | grep BOOST_ | cut -d' ' -f3 | sort
+
+# move to build directory
+mkdir -p "${BOOST_BUILDDIR}"
+cd "${BOOST_BUILDDIR}"
 
 # download boost
-BOOST_URL="${RSTUDIO_BUILDTOOLS}/Boost/${BOOST_TAR}"
-download "${BOOST_URL}"
-
-# remove existing boost directory
-rm -rf "${BOOST_DIR}"
-
-# untar source (remove existing)
-rm -rf "${BOOST_BUILD_DIR}"
-mkdir -p "${BOOST_BUILD_DIR}"
-cd "${BOOST_BUILD_DIR}"
-tar --bzip2 -xf "../$BOOST_TAR"
-
-# change to boost version folder
-cd $BOOST_VERSION
-
-# bootstrap boost
-./bootstrap.sh
-
-# build bcp helper
-./b2 "${TOOLSET}" tools/bcp
-
-# copy back to root
-cp dist/bin/bcp bcp
-
-# use bcp to copy to rstudio folder (use custom namespace)
-mkdir -p rstudio
-
-# shellcheck disable=SC2086
-./bcp --namespace=rstudio_boost --namespace-alias ${BOOST_MODULES[*]} config build rstudio
-
-# move to rstudio folder
-cd rstudio
-
-# bootstrap again
-./bootstrap.sh
-cp b2 bjam
-
-# special variation of build for osx
-if [ "$PLATFORM" = "Darwin" ]; then
-
-   BJAM_CXXFLAGS="cxxflags=-fPIC -std=c++11 -mmacosx-version-min=10.12"
-   BJAM_LDFLAGS=""
-
-   ./bjam                   \
-      "${BOOST_BJAM_FLAGS}" \
-      --prefix="$BOOST_DIR" \
-      "${TOOLSET}"          \
-      "${BJAM_CXXFLAGS}"    \
-      "${BJAM_LDFLAGS}"     \
-      variant=release       \
-      threading=multi       \
-      link=static           \
-      install
-
-else
-
-   # plain old build for other platforms
-   ./bjam                    \
-      "${BOOST_BJAM_FLAGS}"  \
-      --prefix="$BOOST_DIR"  \
-      variant=release        \
-      cxxflags="-fPIC -std=c++11" \
-      install
-
+if ! [ -f "${BOOST_TARBALL}" ]; then
+   subsection "Downloading ${BOOST_URL}"
+   download "${BOOST_URL}"
 fi
 
-# rename libraries in the boost install dir
-cd "$BOOST_DIR/lib"
-for file in librstudio*; do
-   src=$file
-   tgt="${src//rstudio_/}"
-   mv "$src" "$tgt"
-done
+# untar source; removing an existing build directory if one exists
+subsection "Extracting Boost"
+rm -rf "${BOOST_FOLDER}"
+tar --bzip2 -xf "${BOOST_TARBALL}"
+cd "${BOOST_FOLDER}"
 
-for file in libboost*.so; do
-   ln -nfs "$file.$BOOST_VERSION_NUMBER" "$file"
-done
+# use 'rstudio_boost' namespace instead of 'boost'
+subsection "namespace boost => namespace rstudio_boost"
+src="namespace\\s+boost[\\s\\\\]*{"
+tgt="namespace rstudio_boost {} namespace boost = rstudio_boost; namespace rstudio_boost {"
+LC_ALL=C find . -type f \
+   -exec perl -pi -e "BEGIN{undef $/;} s/$src/$tgt/smg" {} + \
+   -exec perl -pi -e "s/\\(boost\\)/(rstudio_boost)/g" {} +
 
-# go back to the original install dir and remove build and tmp dirs
-cd "${INSTALL_DIR}"
-rm -rf "${BOOST_BUILD_DIR}"
-rm -rf "${TEMP_DIR}"
+# bootstrap
+subsection "Bootstrapping Boost"
+./bootstrap.sh --prefix="${BOOST_PREFIX}" --without-icu --without-libraries=graph_parallel,mpi,python
 
-info "Boost ${BOOST_VERSION} installed to '${BOOST_DIR}'"
+# build it
+subsection "Building Boost"
+./b2 -q ${BOOST_EXTRA} variant=release link=static install
+
+# clean up
+cd "${OWD}"
+is-interactive || rm -rf "${BOOST_BUILDDIR}"
+
+# all done
+yay "Boost ${BOOST_VERSION} installed to '${BOOST_PREFIX}'."
 
