no longer require --install-crashpad-sudo

diff --git a/dependencies/common/install-crashpad b/dependencies/common/install-crashpad
--- a/dependencies/common/install-crashpad
+++ b/dependencies/common/install-crashpad
@@ -41,50 +41,59 @@ LLVM_BIN_DIR=$LLVM_DIR/build/bin
 CRASHPAD_DIR=$RSTUDIO_TOOLS_ROOT/crashpad
 CRASHPAD_BIN_DIR=$CRASHPAD_DIR/crashpad/out/Default
 
+# flavor used for prebuilt crashpad binaries
+FLAVOR="$1"
+if is-macos; then
+   FLAVOR=osx
+fi
+
 # check for presence of argument indicating to install pre-built binaries
 # if present, we skip building crashpad altogether and just install from S3
-if test -n "$1"
-then
-   if ! test -e $CRASHPAD_BIN_DIR/crashpad_handler
-   then
-      echo "Installing pre-built Crashpad binaries for $1"
-      if [[ "$1" == "osx" ]]; then
-        ARCHIVE_EXT=.zip
-        ARCHIVE_FOLDER=osx
-      else
-        ARCHIVE_EXT=.tar.gz
-        ARCHIVE_FOLDER=linux
-      fi
+if [ -n "${FLAVOR}" ]; then
 
-      mkdir -p $RSTUDIO_TOOLS_ROOT
-      cd $RSTUDIO_TOOLS_ROOT
-      download "$CRASHPAD_PRE_BUILT_ROOT_URL/$ARCHIVE_FOLDER/crashpad-$1$ARCHIVE_EXT"
-      tar xvf "crashpad-$1$ARCHIVE_EXT"
-      if ! test -e $CRASHPAD_BIN_DIR/crashpad_handler
-      then
-         echo "An error occured installing pre-built Crashpad binaries - $CRASHPAD_BIN_DIR/crashpad_handler does not exist"
-         exit 1
-      else
-         rm "./crashpad-$1$ARCHIVE_EXT"
-         echo "Successfully installed pre-built Crashpad binaries"
-         exit 0
-      fi
-   else
-      echo "Crashpad already installed"
+   if [ -e "${CRASHPAD_BIN_DIR}/crashpad_handler" ]; then
+      echo "Crashpad already installed at '${CRASHPAD_BIN_DIR}'"
       exit 0
    fi
+
+   # re-run as root if necessary
+   require-root-for "${RSTUDIO_TOOLS_ROOT}" "$@"
+
+   echo "Installing pre-built Crashpad binaries for '${FLAVOR}'"
+   if is-macos; then
+      ARCHIVE_EXT=.zip
+      ARCHIVE_FOLDER=osx
+   else
+      ARCHIVE_EXT=.tar.gz
+      ARCHIVE_FOLDER=linux
+   fi
+
+   mkdir -p "$RSTUDIO_TOOLS_ROOT"
+   cd "$RSTUDIO_TOOLS_ROOT"
+   download "$CRASHPAD_PRE_BUILT_ROOT_URL/$ARCHIVE_FOLDER/crashpad-${FLAVOR}$ARCHIVE_EXT"
+   tar xvf "crashpad-${FLAVOR}$ARCHIVE_EXT"
+   if ! test -e "$CRASHPAD_BIN_DIR/crashpad_handler"; then
+      echo "An error occured installing pre-built Crashpad binaries - $CRASHPAD_BIN_DIR/crashpad_handler does not exist"
+      exit 1
+   else
+      rm "./crashpad-${FLAVOR}$ARCHIVE_EXT"
+      echo "Successfully installed pre-built Crashpad binaries to '${CRASHPAD_BIN_DIR}'"
+      exit 0
+   fi
+
 fi
+
+# re-run as root if necessary
+require-root-for "${RSTUDIO_TOOLS_ROOT}" "$@"
 
 # install google depot_tools if not already installed
 # these tools are necessary to properly checkout and build crashpad
-if ! test -e $DEPOT_TOOLS_DIR
-then
-   mkdir -p $DEPOT_TOOLS_DIR
-   cd $DEPOT_TOOLS_DIR
-
+if ! test -e "$DEPOT_TOOLS_DIR"; then
+   mkdir -p "$DEPOT_TOOLS_DIR"
+   cd "$DEPOT_TOOLS_DIR"
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git .
 else
-   echo "depot_tools already installed in $DEPOT_TOOLS_DIR"
+   echo "depot_tools already installed in '$DEPOT_TOOLS_DIR'"
 fi
 
 # build clang if the system does not already have it or the system version is too low
@@ -135,46 +144,44 @@ else
 fi
 
 # install crashpad if we aren't already installed
-if ! test -e $CRASHPAD_BIN_DIR/crashpad_handler
-then
-   mkdir -p $CRASHPAD_DIR
-   cd $CRASHPAD_DIR
-
-   # put depot tools on our path, otherwise they don't run properly
-   export PATH=$PATH:$DEPOT_TOOLS_DIR
-
-   # download crashpad using google tools
-   fetch crashpad || sync crashpad
-
-   # add the rstudio fork and switch to the rstudio branch which
-   # contains all of the patches we need to make it work for us
-   cd crashpad
-   git remote add rstudio https://github.com/rstudio/crashpad.git || true
-   git fetch rstudio
-   git checkout rstudio || true
-   git pull
-
-   if ! $use_system_clang; then
-      # add custom built clang to path so it can be picked up by crashpad build
-      export PATH=$LLVM_BIN_DIR:$PATH
-   fi
-
-   # build crashpad
-   $DEPOT_TOOLS_DIR/gn gen out/Default
-
-   if [[ "$OSTYPE" = "darwin"* ]]; then
-      # on macos, we need to specify the minimum os target to support
-      echo "mac_deployment_target=\"10.12\"" > out/Default/args.gn
-      $DEPOT_TOOLS_DIR/gn gen out/Default
-   fi
-
-   $DEPOT_TOOLS_DIR/ninja -C out/Default
-
-   # fix up permissions (if run as root, bin dir will be unreadable by others)
-   chmod -R 755 out
-else
-   echo "crashpad already installed in $CRASHPAD_BIN_DIR"
+if [ -e "${CRASHPAD_BIN_DIR}/crashpad_handler" ]; then
+   echo "Crashpad already installed at '${CRASHPAD_BIN_DIR}'"
+   exit 0
 fi
 
-# back to install dir
-cd $INSTALL_DIR
+mkdir -p $CRASHPAD_DIR
+cd $CRASHPAD_DIR
+
+# put depot tools on our path, otherwise they don't run properly
+export PATH=$PATH:$DEPOT_TOOLS_DIR
+
+# download crashpad using google tools
+fetch crashpad || sync crashpad
+
+# add the rstudio fork and switch to the rstudio branch which
+# contains all of the patches we need to make it work for us
+cd crashpad
+git remote add rstudio https://github.com/rstudio/crashpad.git || true
+git fetch rstudio
+git checkout rstudio || true
+git pull
+
+if ! $use_system_clang; then
+   # add custom built clang to path so it can be picked up by crashpad build
+   export PATH=$LLVM_BIN_DIR:$PATH
+fi
+
+# build crashpad
+$DEPOT_TOOLS_DIR/gn gen out/Default
+
+if [[ "$OSTYPE" = "darwin"* ]]; then
+   # on macos, we need to specify the minimum os target to support
+   echo "mac_deployment_target=\"10.12\"" > out/Default/args.gn
+   $DEPOT_TOOLS_DIR/gn gen out/Default
+fi
+
+$DEPOT_TOOLS_DIR/ninja -C out/Default
+
+# fix up permissions (if run as root, bin dir will be unreadable by others)
+chmod -R 755 out
+
