Open source companion commit for https://github.com/rstudio/rstudio-pro/pull/255. Some fixes for the Spawner process code and enabling unit testing in CI builds

diff --git a/src/cpp/rstudio-tests.in b/src/cpp/rstudio-tests.in
--- a/src/cpp/rstudio-tests.in
+++ b/src/cpp/rstudio-tests.in
@@ -1,5 +1,13 @@
 #!/usr/bin/env sh
 
+checkUnitTestFailure() {
+   RET_CODE=$?
+   if [ $RET_CODE != 0 ];
+   then
+      UNIT_TEST_FAILURE=true
+   fi
+}
+
 ## Any arguments passed in are considered arguments to valgrind
 if [ "$#" -eq 0 ]; then
 	VALGRIND=
@@ -18,11 +26,46 @@ else
     RSTUDIO_SESSION_BIN="rsession"
 fi
 
+
 echo Running 'core' tests...
 $VALGRIND ${CMAKE_CURRENT_BINARY_DIR}/core/$RSTUDIO_CORETEST_BIN
+checkUnitTestFailure
 
 echo Running 'rsession' tests...
+if [ -e ${CMAKE_CURRENT_BINARY_DIR}/conf/rdesktop-dev.conf ]
+then
+   SESSION_CONF_FILE=${CMAKE_CURRENT_BINARY_DIR}/conf/rdesktop-dev.conf
+else
+   SESSION_CONF_FILE=${CMAKE_CURRENT_BINARY_DIR}/conf/rsession-dev.conf
+fi
+   
 $VALGRIND ${CMAKE_CURRENT_BINARY_DIR}/session/$RSTUDIO_SESSION_BIN \
-    --run-tests \
-    --config-file=${CMAKE_CURRENT_BINARY_DIR}/conf/rdesktop-dev.conf
+   --run-tests \
+   --config-file=$SESSION_CONF_FILE
+checkUnitTestFailure
 
+if [ -e ${CMAKE_CURRENT_BINARY_DIR}/server/filebase ]
+then
+    echo Running 'filebase' tests...
+    $VALGRIND ${CMAKE_CURRENT_BINARY_DIR}/server/filebase/filebase-tests
+fi
+checkUnitTestFailure
+
+if [ -e ${CMAKE_CURRENT_BINARY_DIR}/spawner ]
+then
+   echo Running 'spawner' tests...
+   sudo $VALGRIND ${CMAKE_CURRENT_BINARY_DIR}/spawner/spawner-tests
+   checkUnitTestFailure
+
+   echo Running 'local spawner' tests
+   sudo $VALGRIND ${CMAKE_CURRENT_BINARY_DIR}/spawner/impls/local/local-spawner-tests
+   checkUnitTestFailure
+fi
+
+# return an error exit code if any unit tests failed
+if [ "$UNIT_TEST_FAILURE" = true ] ; then
+    exit 1
+fi
+
+# otherwise, return success
+exit 0
