Add RSTUDIO_TARGET=Electron, plumb in osx make-package

diff --git a/package/osx/make-package b/package/osx/make-package
--- a/package/osx/make-package
+++ b/package/osx/make-package
@@ -96,6 +96,7 @@ clean=0
 copy_gwt=1
 install=0
 use_creds=0
+rstudio_target=Desktop
 
 # by default, use RStudio credentials for builds on Jenkins
 if [ -n "${JENKINS_URL}" ]; then
@@ -106,18 +107,25 @@ fi
 for arg in "$@"; do
 
    case "$arg" in
-   clean)             clean=1 ;;
-   --arch=*)          arch=${arg#*=} ;;
-   --clean)           clean=1 ;;
-   --install)         install=1 ;;
-   --build-gwt=*)     build_gwt=${arg#*=} ;;
-   --copy-gwt=*)      copy_gwt=${arg#*=} ;;
-   --build-package=*) build_package=${arg#*=} ;;
-   --build-dmg=*)     build_dmg=${arg#*=} ;;
-   --use-creds=*)     use_creds=${arg#*=} ;;
+   clean)              clean=1 ;;
+   --arch=*)           arch=${arg#*=} ;;
+   --clean)            clean=1 ;;
+   --install)          install=1 ;;
+   --build-gwt=*)      build_gwt=${arg#*=} ;;
+   --copy-gwt=*)       copy_gwt=${arg#*=} ;;
+   --build-package=*)  build_package=${arg#*=} ;;
+   --build-dmg=*)      build_dmg=${arg#*=} ;;
+   --use-creds=*)      use_creds=${arg#*=} ;;
+   --rstudio-target=*) rstudio_target=${arg#*=} ;;
    esac
 
 done
+
+if [ "${rstudio_target}" != "Desktop" ] && [ "${rstudio_target}" != "Electron" ]
+then
+   echo "error: must specify --rstudio-target=Desktop|Electron (default Desktop)"
+   exit 1
+fi
 
 case "${arch}" in *arm64*)  build_arm64=1  ;; esac
 case "${arch}" in *x86_64*) build_x86_64=1 ;; esac
@@ -175,7 +183,7 @@ if [ -n "${build_x86_64}" ]; then
       -DCMAKE_BUILD_TYPE=RelWithDebInfo                      \
       -DCMAKE_OSX_DEPLOYMENT_TARGET="10.12"                  \
       -DCMAKE_INSTALL_PREFIX="${PKG_DIR}/install"            \
-      -DRSTUDIO_TARGET=Desktop                               \
+      -DRSTUDIO_TARGET=${rstudio_target}                     \
       -DRSTUDIO_PACKAGE_BUILD=1                              \
       -DRSTUDIO_CRASHPAD_ENABLED=0                           \
       -DRSTUDIO_TOOLS_ROOT="${RSTUDIO_TOOLS_ROOT}/../x86_64" \
