update pre-commit failure and output separator logic

diff --git a/git_hooks/hooks/pre-commit b/git_hooks/hooks/pre-commit
--- a/git_hooks/hooks/pre-commit
+++ b/git_hooks/hooks/pre-commit
@@ -1,25 +1,40 @@
 #!/bin/sh
 
 # A pre-commit hook script to:
-#  -  run linting and formatting on staged files based on the lint-staged,
-#     prettier and eslint configurations in src/node/desktop.
-#  -  run detect-secrets on staged files to check for secrets.
+#  - run linting and formatting on staged files based on the lint-staged,
+#    prettier and eslint configurations in src/node/desktop.
+#  - run detect-secrets on staged files to check for secrets.
+# This script will run all applicable hooks and fails the commit afterwards if any of the hooks fail.
 
 color_error='\033[1;31m' # red
 color_highlight='\033[1;95m' # magenta
 color_none='\033[0m' # no color
 repo_root=$(git rev-parse --show-toplevel)
 
-previous_hook_run=false
+fail_precommit=false # will be set to true if the pre-commit hook should fail at the end
 
 hook_setup() {
     cd "$repo_root"
+    # Print a separator line before the output of each hook
+    echo "${color_highlight}------${color_none}"
+}
 
-    # Print a separator between hooks
-    if [ "$previous_hook_run" = true ]; then
-        echo "${color_highlight}------${color_none}"
+precommit_exit() {
+    hook_setup
+    if [ "$fail_precommit" = true ]; then
+        echo >&2 "${color_error}pre-commit hook failed.${color_none}"
+        exit 1
+    else
+        echo "${color_highlight}pre-commit hook complete.${color_none}"
+        exit 0
     fi
 }
+
+echo "${color_highlight}Running pre-commit hook...${color_none}"
+
+#####################################
+#          Add hooks below          #
+#####################################
 
 # Linting and formatting on RStudio Desktop IDE files
 if test -f ./src/node/desktop/.lintstagedrc
@@ -27,8 +42,10 @@ then
     hook_setup
     if git diff --staged --name-only | grep -qE '^src/node/desktop/.*'
     then
-        previous_hook_run=true
         cd ./src/node/desktop && npx lint-staged
+        if [ $? -ne 0 ]; then
+            fail_precommit=true
+        fi
     fi
 else
     echo >&2 "${color_highlight}Note: src/node/desktop linting pre-commit hook is not being run because ${color_none}.lintstagedrc${color_highlight} was not found.${color_none}"
@@ -42,17 +59,20 @@ then
 else
     hook_setup
     echo "Running detect-secrets-hook on staged files..."
-    previous_hook_run=true
     secrets_results=$(./git_hooks/secrets/run-detect-secrets run-hook)
     if [ -n "$secrets_results" ]; then
-        echo "detect-secrets-hook results:\n"
-        echo "${color_error}Uh oh! It looks like you have secrets in your code. Please remove them before committing.${color_none}"
+        fail_precommit=true
+        echo "\n${color_error}Uh oh! It looks like you have secrets in your code. Please remove them before committing.${color_none}"
         echo "If you are certain that these are false positives, see git_hooks/secrets/README.md for instructions on how to mark them as such.\n"
         echo "$secrets_results"
-        exit 1
     else
         echo "🎉 No secrets found!"
     fi
 fi
 
-exit 0
+#####################################
+#          Add hooks above          #
+#####################################
+
+# This should be the last line of this file
+precommit_exit
