Qt 5.11.1
- switch to MSVC 2017 on Windows
- switch to cmake 3.1.0 or above
- new xenial dockerfile
- trusty and opensuse docker builds stay on Qt 5.10.1 due to linker issues; will open issues to track
- remove Linux workaround for Qt 5.10.1 bug that prevented finding QtWebEngineProcess if sandboxing enabled
- install Qt via online installer in dockerfiles and dependency scripts
- option to use packaged download of Qt (way we used to do it)
- work in progress batch file for running Windows docker builds (works but requires juggling, described in batch file comments)
- created separate install-qt batch file for Windows, instead of doing it directly in install-dependencies batch file

diff --git a/dependencies/linux/install-qt-sdk b/dependencies/linux/install-qt-sdk
--- a/dependencies/linux/install-qt-sdk
+++ b/dependencies/linux/install-qt-sdk
@@ -13,39 +13,146 @@
 # MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 # AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
 #
-#
 
-# This archive includes the files required to build against Qt. It
-# was created by installing Qt via an interactive installer, and 
-# manually removing components not needed by RStudio.
-
-# define QT archive to download
-SYSTEM_ARCH=`getconf LONG_BIT`
-if [ "$SYSTEM_ARCH" == "64" ]
-then
-  QT_ARCH=x86_64
+if [ -z "$QT_VERSION" ]; then
+    QT_VERSION=5.11.1
+fi
+if [ -z "$QT_SDK_BINARY" ]; then
+    QT_SDK_BINARY=qt-unified-linux-x64-3.0.5-online.run
+fi
+if [ -z "$QT_PACKAGES" ]; then
+    QT_PACKAGES=qt.qt5.5111.gcc_64,qt.qt5.5111.qtwebengine,qt.qt5.5111.qtwebengine.gcc_64
+fi
+if [ -z "$QT_SDK_CUSTOM" ]; then
+    echo Using online Qt installer
 else
-  QT_ARCH=x86
+    echo Using custom Qt package: $QT_SDK_CUSTOM
 fi
-
-QT_VERSION=5.10.1
-QT_SDK_BINARY=QtSDK-${QT_VERSION}-${QT_ARCH}.tar.gz
-QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
-
-# set Qt SDK dir if not already defined
 if [ -z "$QT_SDK_DIR" ]; then
-  QT_SDK_DIR=~/Qt${QT_VERSION}
-  QT_SDK_DIR2=~/Qt/Qt${QT_VERSION}
-  QT_SDK_DIR3=~/Qt/${QT_VERSION}
+
+   # Qt install root if path not supplied
+   QT_SDK_DIR=~/Qt${QT_VERSION}
+   
+   # other locations checked for existing installation
+   QT_SDK_DIR2=~/Qt/Qt${QT_VERSION}
+   QT_SDK_DIR3=~/Qt/${QT_VERSION}
 fi
+
+QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
+QT_SCRIPT=/tmp/qt-noninteractive-install-linux.qs
+
+# generate script for automatic Qt installation; customizes the install location via $QT_SDK_DIR
+function write_qt_script() {
+cat << EOF > $QT_SCRIPT
+
+function Controller() {
+    installer.autoRejectMessageBoxes();
+    installer.installationFinished.connect(function() {
+        gui.clickButton(buttons.NextButton);
+    })
+    installer.setMessageBoxAutomaticAnswer("cancelInstallation", QMessageBox.Yes);
+}
+
+Controller.prototype.WelcomePageCallback = function() {
+    gui.clickButton(buttons.NextButton, 3000);
+}
+
+Controller.prototype.CredentialsPageCallback = function() {
+    var widget = gui.currentPageWidget();
+    widget.loginWidget.EmailLineEdit.setText("");
+    widget.loginWidget.PasswordLineEdit.setText("");
+    gui.clickButton(buttons.NextButton, 500);
+}
+
+Controller.prototype.IntroductionPageCallback = function() {
+    gui.clickButton(buttons.NextButton);
+}
+
+Controller.prototype.TargetDirectoryPageCallback = function()
+{
+    var widget = gui.currentPageWidget();
+    if (widget != null) {
+        widget.TargetDirectoryLineEdit.setText("$QT_SDK_DIR");
+    }
+    gui.clickButton(buttons.NextButton);
+}
+
+Controller.prototype.ComponentSelectionPageCallback = function() {
+    var widget = gui.currentPageWidget();
+
+    function trim(str) {
+        return str.replace(/^ +/,"").replace(/ *$/,"");
+    }
+
+    var packages = trim("$QT_PACKAGES").split(",");
+    if (packages.length > 0 && packages[0] !== "") {
+        widget.deselectAll();
+        for (var i in packages) {
+            var pkg = trim(packages[i]);
+            widget.selectComponent(pkg);
+        }
+    }
+    gui.clickButton(buttons.NextButton);
+}
+
+Controller.prototype.LicenseAgreementPageCallback = function() {
+    gui.currentPageWidget().AcceptLicenseRadioButton.setChecked(true);
+    gui.clickButton(buttons.NextButton);
+}
+
+Controller.prototype.StartMenuDirectoryPageCallback = function() {
+    gui.clickButton(buttons.NextButton);
+}
+
+Controller.prototype.ReadyForInstallationPageCallback = function()
+{
+    gui.clickButton(buttons.NextButton);
+}
+
+Controller.prototype.FinishedPageCallback = function() {
+    var checkBoxForm = gui.currentPageWidget().LaunchQtCreatorCheckBoxForm
+    if (checkBoxForm && checkBoxForm.launchQtCreatorCheckBox) {
+        checkBoxForm.launchQtCreatorCheckBox.checked = false;
+    }
+    gui.clickButton(buttons.FinishButton);
+}
+EOF
+}
 
 if [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]
 then
-   # download and install
-   wget $QT_SDK_URL -O /tmp/$QT_SDK_BINARY
-   cd `dirname $QT_SDK_DIR`
-   tar xzf /tmp/$QT_SDK_BINARY
-   rm /tmp/$QT_SDK_BINARY
+   if [ -z "$QT_SDK_CUSTOM" ]; then
+      # download and install via Qt online installer
+      wget $QT_SDK_URL -O /tmp/$QT_SDK_BINARY
+      chmod u+x /tmp/$QT_SDK_BINARY
+      write_qt_script
+
+      # online installer sometimes fails, keep trying...
+      retryCounter=0
+      while [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ] && [ $retryCounter -le 5 ] 
+      do
+         echo "Installing Qt, this will take a while."
+         echo " - Ignore warnings about QtAccount credentials and/or XDG_RUNTIME_DIR."
+         echo " - Do not click on any Qt setup dialogs, it is controlled by a script."
+         /tmp/$QT_SDK_BINARY --script $QT_SCRIPT
+         ((retryCounter++))
+      done
+      rm -f /tmp/$QT_SDK_BINARY $QT_SCRIPT
+   else
+      QT_SDK_BINARY=$QT_SDK_CUSTOM
+      QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
+      
+      # download and install
+      wget $QT_SDK_URL -O /tmp/$QT_SDK_BINARY
+      cd `dirname $QT_SDK_DIR`
+      tar xzf /tmp/$QT_SDK_BINARY
+      rm /tmp/$QT_SDK_BINARY
+   fi
+      
+   if [ ! -e "$QT_SDK_DIR" ] && [ ! -e "$QT_SDK_DIR2" ] && [ ! -e "$QT_SDK_DIR3" ]; then
+      echo "Error: Unable to install Qt, run script again or install manually." 
+      exit 1
+   fi
 else
    echo "Qt $QT_VERSION SDK already installed"
 fi
